// Servis kayıtları için veri modeli ve başlangıç verileri

export const QUICK_SERVICES = [
  'Yağ Değişimi',
  'Yağ Filtresi',
  'Hava Filtresi',
  'Yakıt Filtresi',
  'Polen Filtresi',
  'Fren Balatası',
  'İşçilik',
];

export const OIL_BRANDS = [
  'Castrol 5W-30',
  'Castrol 10W-40',
  'Mobil 1 0W-40',
  'Mobil 1 5W-30',
  'Motul 8100 5W-40',
  'Shell Helix 5W-30',
  'Total Quartz 5W-40',
  'Petronas 5W-30',
];

export const INITIAL_RECORDS = [
  {
    id: '1',
    customerName: 'Ahmet Yılmaz',
    customerPhone: '0532 123 45 67',
    plate: '34 ABC 123',
    brand: 'BMW',
    model: '320d',
    year: '2020',
    kilometer: '145.000',
    date: '2024-03-12',
    oilBrand: 'Castrol 5W-30',
    oilViscosity: '5W-30',
    services: [
      { name: 'Yağ ve Filtre Değişimi', description: 'Periyodik bakım kapsamında', price: 1200 },
      { name: 'Fren Balata Kontrolü', description: 'Ön ve arka diskler temizlendi', price: 450 },
      { name: 'Ön Düzen Ayarı', description: 'Rot-balans hassas ayar', price: 1200 },
    ],
    items: [
      { name: 'Motor Yağı', quantity: 4, unitPrice: 350, total: 1400 },
      { name: 'Yağ Filtresi', quantity: 1, unitPrice: 220, total: 220 },
    ],
    notes: 'Aracın alt takımları genel olarak iyi durumda. Bir sonraki bakımda arka amortisörlerin kontrol edilmesi önerilir. Lastik basınçları 32 PSI olarak ayarlandı.',
    laborTotal: 450,
    partsTotal: 1620,
    totalAmount: 12450,
    status: 'completed',
    paymentStatus: 'paid',
    paidAmount: 12450,
  },
  {
    id: '2',
    customerName: 'Mehmet Demir',
    customerPhone: '0543 234 56 78',
    plate: '06 DET 789',
    brand: 'Mercedes',
    model: 'C200',
    year: '2019',
    kilometer: '98.000',
    date: '2024-03-08',
    oilBrand: 'Mobil 1',
    oilViscosity: '0W-40',
    services: [
      { name: 'Yağ ve Filtre Değişimi', description: 'Tam sentetik yağ değişimi', price: 1800 },
      { name: 'Hava Filtresi Değişimi', description: 'Orijinal parça takıldı', price: 650 },
      { name: 'Klima Bakımı', description: 'Gaz dolumu ve dezenfeksiyon', price: 1200 },
    ],
    items: [
      { name: 'Motor Yağı', quantity: 5, unitPrice: 420, total: 2100 },
      { name: 'Yağ Filtresi', quantity: 1, unitPrice: 380, total: 380 },
      { name: 'Hava Filtresi', quantity: 1, unitPrice: 320, total: 320 },
    ],
    notes: 'Klima sisteminde gaz kaçağı tespit edildi. Geçici tamir yapıldı, kalıcı çözüm için kompresör değişimi önerilir.',
    laborTotal: 850,
    partsTotal: 2800,
    totalAmount: 4800,
    status: 'completed',
    paymentStatus: 'partial',
    paidAmount: 3000,
  },
  {
    id: '3',
    customerName: 'Canan Özkan',
    customerPhone: '0555 345 67 89',
    plate: '35 IZM 44',
    brand: 'Volkswagen',
    model: 'Golf',
    year: '2021',
    kilometer: '62.000',
    date: '2024-03-01',
    oilBrand: 'Motul 8100',
    oilViscosity: '5W-40',
    services: [
      { name: 'Periyodik Bakım', description: 'Full bakım paketi', price: 3500 },
      { name: 'Fren Disk Değişimi', description: 'Ön fren diskleri değiştirildi', price: 2800 },
      { name: 'Balata Değişimi', description: 'Ön balatalar değiştirildi', price: 1200 },
    ],
    items: [
      { name: 'Motor Yağı', quantity: 4, unitPrice: 380, total: 1520 },
      { name: 'Fren Diski', quantity: 2, unitPrice: 1400, total: 2800 },
      { name: 'Fren Balatası', quantity: 1, unitPrice: 650, total: 650 },
    ],
    notes: 'Araç genel bakımdan geçti. Arka fren diskleri de yakında değiştirilmeli. Akü durumu iyi.',
    laborTotal: 1200,
    partsTotal: 4970,
    totalAmount: 8200,
    status: 'completed',
    paymentStatus: 'unpaid',
    paidAmount: 0,
  },
  {
    id: '4',
    customerName: 'Mehmet Yılmaz',
    customerPhone: '0532 987 65 43',
    plate: '34 ABC 123',
    brand: 'BMW',
    model: '320d',
    year: '2020',
    kilometer: '150.000',
    date: '2024-06-10',
    oilBrand: 'Castrol',
    oilViscosity: '5W-30',
    services: [
      { name: 'Yağ ve Filtre Değişimi', description: 'Periyodik bakım kapsamında', price: 1200 },
    ],
    items: [
      { name: 'Motor Yağı', quantity: 4, unitPrice: 350, total: 1400 },
      { name: 'Yağ Filtresi', quantity: 1, unitPrice: 100, total: 100 },
    ],
    notes: '',
    laborTotal: 0,
    partsTotal: 1500,
    totalAmount: 1500,
    status: 'completed',
    paymentStatus: 'paid',
    paidAmount: 1500,
  },
  {
    id: '5',
    customerName: 'Ayşe Demir',
    customerPhone: '0544 111 22 33',
    plate: '06 DEF 456',
    brand: 'Toyota',
    model: 'Corolla',
    year: '2022',
    kilometer: '35.000',
    date: '2024-06-09',
    oilBrand: 'Shell Helix',
    oilViscosity: '5W-30',
    services: [
      { name: 'Yağ ve Filtre Değişimi', description: 'Periyodik bakım', price: 950 },
      { name: 'Fren Balata Kontrolü', description: 'Kontrol ve temizlik', price: 300 },
      { name: 'Lastik Rotasyonu', description: 'Dört lastik rotasyonu yapıldı', price: 200 },
    ],
    items: [
      { name: 'Motor Yağı', quantity: 4, unitPrice: 320, total: 1280 },
      { name: 'Yağ Filtresi', quantity: 1, unitPrice: 180, total: 180 },
    ],
    notes: 'Lastikler düzgün aşınıyor. Bir sonraki bakımda hava filtresi değiştirilmeli.',
    laborTotal: 450,
    partsTotal: 1460,
    totalAmount: 4250,
    status: 'completed',
    paymentStatus: 'paid',
    paidAmount: 4250,
  },
  {
    id: '6',
    customerName: 'Caner Özkan',
    customerPhone: '0533 444 55 66',
    plate: '35 GHI 789',
    brand: 'Renault',
    model: 'Megane',
    year: '2018',
    kilometer: '112.000',
    date: '2024-06-08',
    oilBrand: 'Total Quartz',
    oilViscosity: '5W-40',
    services: [
      { name: 'Motor Bakımı', description: 'Genel motor kontrolü', price: 850 },
    ],
    items: [],
    notes: 'Motor sesleri kontrol edildi, sorun bulunamadı.',
    laborTotal: 850,
    partsTotal: 0,
    totalAmount: 850,
    status: 'completed',
    paymentStatus: 'partial',
    paidAmount: 500,
  },
];

// Atölye durumu istatistikleri
export const WORKSHOP_STATS = {
  inRepair: 12,
  readyForDelivery: 5,
  waiting: 8,
};

// Yeni boş kayıt şablonu
export function createEmptyRecord() {
  return {
    id: Date.now().toString(),
    customerName: '',
    customerPhone: '',
    plate: '',
    brand: '',
    model: '',
    year: '',
    kilometer: '',
    date: new Date().toISOString().split('T')[0],
    oilBrand: '',
    oilViscosity: '',
    services: [],
    items: [],
    notes: '',
    laborTotal: 0,
    partsTotal: 0,
    totalAmount: 0,
    status: 'in_progress',
    paymentStatus: 'unpaid',
    paidAmount: 0,
  };
}
